### PR TITLE
Sanitize code

### PR DESCRIPTION
**Pull request by shrx**
Part 2 - version r8y2

### CODE REVIEW

**Comment by Gordon999** [comment]
I have also found it corrupts the stored configs eg config1.txt by writing True / False instead of 1/0 for some parameters. It appears to be where you have used 'thres = not thres' etc which then uses True/False not 1/0

**Comment by shrx** [comment]
Yeah python automatically converts 0 and 1 to True and False in such cases. You can use `int(True)` and `int(False)` to get 1 and 0. Will include this in the fix.

**Comment by shrx** [comment]
I have removed the two leftover `change` definitons and the syntax for saving the config files should now be correct.
I still have to find the cause of the mis-alignment of key numbers - the `keys2()` function definition does not appear to be meaningfully different as in the [bc70945](https://github.com/Gordon999/Pi-AutoGuider/blob/bc709455acd7208212550fd3e2c06cb9609480b6/PiAGr8w3.py) commit (autoguider version r8w3).

**Comment by shrx** [comment]
After comparing the screenshot with the actual GUI, it seems that only some keys are shifted, for example

```
keys2(str(zoom),                  fs,       3,        b1x,         bw,   5,     b1y, bh, 6, 3, 0)
```

is shifted, but

```
keys2("Zoom",                     fs,       6,        b1x,         bw,   4,     b1y, bh, 6, 0, 0)
```

is not. Will investigate.

**Comment by Gordon999** [comment]
If you cut and paste in the original def Keys section , it works OK.

**Comment by shrx** [comment]
OK, will go over it again.

**Comment by shrx** [comment]
Found it, fixed.

**Pull request merged**
